config/routes.rb
Harvest::Application.routes.draw do
	match 'login' => "users#login"
	match 'logout' => "users#logout"

	resources :users do
		post :create_session, :on => :collection
	end

	resources :sections do 
		resources :folders do
			post :sort, :on => :collection
			resources :pages
			resources :boards do
				resources :posts
			end
		end
	end

	resources :questions, :comments, :assets
	
	match "editor/:action", :controller => :editor, :as => :editor, :via => [:get, :post]

	match 'new_question' => "main#new_question", :as => 'new_question'
	match 'question' => "main#question", :via => [:post], :as => 'question'
	match 'new_rsvp' => "main#new_rsvp", :as => 'new_rsvp'
	match 'rsvp' => "main#rsvp", :via => [:post], :as => 'rsvp'

	match 'company' => "main#company", :as => 'company'

	root :to => "main#index"	
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  has_attached_file :attachment, :styles => { :big => "640x480", :standard => "480x360>" }
end

app/models/board.rb
class Board < ActiveRecord::Base
	
	belongs_to :folder, :counter_cache => true
	has_many :posts, :dependent => :destroy

	def is_admin_only?
		NoticeBoardIDs.include? self.id
	end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :post, :counter_cache => true
	belongs_to :user

	def owned_by?(u)
		!u.blank? && (self.user == u || u.is_admin?)
	end

end

app/models/folder.rb
class Folder < ActiveRecord::Base

	belongs_to :section, :counter_cache => true
	has_many :pages, :dependent => :destroy
	has_many :boards, :dependent => :destroy

	acts_as_list

	scope :sequence, :order => "position asc"

	def has_multiple_items?
		self.has_multiple_pages? || self.has_multiple_boards? || self.has_both_of_page_and_board?
	end

	def has_page?
		self.pages_count > 0
	end

	def has_multiple_pages?
		self.pages_count >= 2
	end

	def has_board?
		self.boards_count > 0
	end

	def has_multiple_boards?
		self.boards_count >= 2
	end

	def has_both_of_page_and_board?
		self.has_page? && self.has_board?
	end

end

app/models/page.rb
# encoding: UTF-8
class Page < ActiveRecord::Base
	validates_presence_of :title, :message => "제목을 입력해주세요"

	belongs_to :section
	belongs_to :folder, :counter_cache => true

end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user
	belongs_to :board, :counter_cache => true
	has_many :comments, :dependent => :destroy

  has_attached_file :attachment

	def self.per_page
		15
	end

	def has_attachment?
		!self.attachment_file_name.blank? && !self.attachment_file_size.zero?
	end

	def owned_by?(u)
		!u.blank? && (self.user == u || u.is_admin?)
	end

end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/section.rb
class Section < ActiveRecord::Base

	has_many :folders, :dependent => :destroy

	def has_folder?
		self.folders_count > 0
	end

end

app/models/user.rb
# encoding: UTF-8
class User < ActiveRecord::Base

	validates_presence_of     :email, :message => "이메일을 입력해주세요."
  validates_format_of       :email, :with => /\A[\w\.%\+\-]+@(?:[A-Z0-9\-]+\.)+(?:[A-Z]{2}|com|org|net|edu|gov|mil|biz|info|mobi|name|aero|jobs|museum)\z/i, :message => "알 수 없는 형식의 이메일주소입니다."
  validates_uniqueness_of   :email, :message => "이메일이 이미 사용 중입니다."
  validates_length_of       :password, :within => 4..40, :message => "암호를 4~40자로 입력해주세요."

	attr_accessor :password_confirmation

	def self.authenticate(attrs)
		u = find_by_login(attrs[:login])
		u && u.password == attrs[:password] ? u : nil
	end

	def is_admin?
		self.level >= 9
	end

	protected
		def validate
			errors.add(:passowrd, "암호와 재확인이 다릅니다.") if self.password != @password_confirmation && self.from_crowd?
		end
end

app/controllers/main_controller.rb
# encoding: UTF-8
class MainController < ApplicationController

	def question
		Thread.new do
			UserMailer.question(params).deliver
		end

		flash[:notice] = "문의 메일이 전송되었습니다."
		redirect_to "/sections/5"
	end

	def rsvp
		Thread.new do
			UserMailer.rsvp(params).deliver
		end

		flash[:notice] = "컨퍼런스 참가 신청이 완료되었습니다."
		redirect_to "/sections/5/folders/9/boards/2/posts/28"
	end

end

app/helpers/application_helper.rb
# encoding: UTF-8
module ApplicationHelper

	def add_query(options = {})
		specified_url = options.delete(:url) || request.path
		if options.delete(:clear).blank?
			queries = (options.inject(h = {}) {|h,v| h.merge(v[0].to_s => v[1])}).reverse_merge(request.query_parameters)
		else
			queries = (options.inject(h = {}) {|h,v| h.merge(v[0].to_s => v[1])})
		end

		"#{specified_url}?#{queries.to_param}"
	end

	def admin_actions(extra = "")
		if logged_in_as_admin?
			("<div class='admin_actions'>" +
				"#{link_to_function "폴더이름변경", "zLayer.open(event, '#{edit_section_folder_path(@section, @folder)}')", :class => "link"}" +
				"#{link_to "새로운 페이지", new_section_folder_page_path(@section, @folder), :class => "link"}" +
				"#{link_to_function "게시판추가", "zLayer.open(event, '#{new_section_folder_board_path(@section, @folder)}')", :class => "link"}" +
				extra +
			"</div>").html_safe
		end
	end

	def return_url(default = "/")
		return_to = session[:return_to] || default
		session[:return_to] = session[:previous] = nil
		return_to
	end

	def cancel_to(url = nil)
		url ||= return_url
		content_tag :input, nil, :type => "button", :class => "zButton spacer", :value => "취소", :onclick => "location.href='#{url}'"
	end

	def mouseover
		{ :onmouseover => "mOver(this)", :onmouseout => "mOut(this)" }
	end

	def nl2br(text)
		text.gsub(/[\n]/, "<br/>").html_safe
	end

	def br2space(text)
		text.gsub(/<br.?>/i,' ')
	end

	def dtime_in_words(from_time)
		(distance_of_time_in_words(from_time, Time.now).gsub(/[a-z]+/i) do |m|
			{'years'=>'^년', 'year'=>'^년', 'days'=>'^일', 'day'=>'^일', 'about'=>'약 ','second'=>'^초','seconds'=>'^초','minute'=>'^분','minutes'=>'^분','hour'=>'^시간','hours'=>'^시간','a'=>1}[m]
		end).gsub(/\s\^/,'') + " 전"
	end

	def	logged_in_as_admin?
		!@current_user.blank? && @current_user.is_admin?
	end

	def	logged_in?
		!@current_user.blank?
	end

	def flash_messages
		if flash[:error]
			fl = flash[:error]
			flash[:error] = nil
		elsif flash[:notice]
			fl = flash[:notice]
			flash[:notice] = nil
		end
		fl
	end

end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/editor_helper.rb
module EditorHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/main/_header.html.erb
<h1><%= link_to "하비스트", root_path, :hidefocus => "true" %></h1>

<div class="top_actions">

	<iframe src="http://www.facebook.com/plugins/like.php?href=http://www.facebook.com/pages/Harvestkorea/167090470010539&amp;layout=button_count&amp;show_faces=false&amp;width=450&amp;action=like&amp;colorscheme=light&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:21px;" allowTransparency="true"></iframe>

	<% if logged_in? %>
		<%= link_to "로그아웃", logout_path, :class => "logout", :hidefocus => "true" %>  
		<%# link_to "계정설정", edit_user_path(@current_user.id) %> 
		<%# link_to "회원탈퇴", user_path(@current_user.id), :remote => true, :method=> :delete, :confirm => "정말 탈퇴하시겠습니까?", :class => "link" %> 
	<% else %>
		<%= link_to "로그인", login_path, :class => "login", :hidefocus => "true" %>
		<%= link_to "회원가입", new_user_path, :class => "signup", :hidefocus => "true" %>
	<% end %>

	<%= link_to "공지사항", "/sections/5/folders/9", :class => "announcement", :hidefocus => "true" %>
	<%= link_to "회사소개", "/company", :class => "company", :hidefocus => "true" %>
</div>

<% if params[:controller] == "main" && params[:action] == "index" %>
  <%= content_tag(:div, "", :id => "main_image")  %>
  <div class="main_banner">
    <%= link_to (image_tag "/images/banners/conference_banner.gif"), "http://harvest.co.kr/sections/5/folders/9/boards/2/posts/28" %>
  </div>
<% end %>

<div class="sections">
	<% Section.all.each_with_index do |s, i| %>
		<div class="section">
			<%= link_to s.name, section_path(s), :hidefocus => "true", :class => "section s_#{s.id} #{"showing" if !@section.blank? && @section == s}", :onmouseover => "show_folder_container('#{s.id}')" %>

			<div id="folder_container_<%=i+1%>" class="fragile do_hide section_<%=i+1%> folder_container" style="display:none;">
				<% s.folders.sequence.each_with_index do |f,j| %>
					<%= link_to f.name, [s, f], :class => "#{"showing" if !@folder.blank? && @folder == f} folder_#{j+1}", :hidefocus => "true" %>
				<% end %>
			</div>
		</div>

	<% end %>
</div>

app/views/main/_rail.html.erb
<div id="rail">
	
	<% if !@section.blank? && !@folder.blank? %>
		<div class="folder_title">
			<%= link_to "", @section, :class => "ft_#{@folder.id}" %>
		</div>
	<% end %>

	<% if !@folder.blank? && @folder.has_multiple_items? %>
		<div class="sub_pages">
			<% @folder.pages.each_with_index do |pg,i| %>
				<%= link_to pg.title, [@folder.section, @folder, pg], :hidefocus => "true", :class => "sub_page f#{@folder.id}_page_#{i+1} #{"showing" if !@page.blank? && @page == pg}" %>
			<% end %>

			<% @folder.boards.each do |b| %>
				<%= link_to b.title, [@folder.section, @folder, b], :hidefocus => "true", :class => "sub_page f#{@folder.id}_board_#{i+1} #{"showing" if !@board.blank? && @board == b}" %>
			<% end %>
		</div>
	<% end %>

	<% if logged_in_as_admin? %>
		<%= form_for [@section, @section.folders.new], :remote => true, :html => { :onsubmit => "zLoading();" } do |f| %>
			<div class="hidden">
				<%= f.text_field :section_id %>
			</div>

			<div class="field">
				<%= f.text_field :name, :class => "text control_placeholder", :placeholder => "폴더이름..", :autocomplete => "off" %>
			</div>

			<div class="actions ph_child">
				<%= submit_tag("생성", :class => "zButton right") %>
			</div>
		<% end %>
	<% end %>

	<%= javascript_tag("initSortableFolders();") if logged_in_as_admin? %>

</div>

app/views/main/company.html.erb
<%# render :partial => '/main/rail' %>

<div id="main_wrapper">

	<div class="main_container">


    <h4>[하비스트 한국지사 ㈜미라 소개]</h4> 
    <br> 
    CEO 인사말.<br> 
    <br> 
    언제나 저희 ㈜미라를 믿고 관심과 성원을 보내주신 여러분께 진심으로 감사 드립니다.<br> 
    <br> 
    25년간 Dermatology, P.S. 기자재 및 의료사업으로 외길을 걸어온 ㈜미라는 아무도 개척하지 <br> 
    않은 미지의 시장을 개발해 나가는 데서 보람과 자부심을 느끼고 있습니다.<br> 
    <br> 
    저희 ㈜미라가 Dermatology Laser 및 기자재, 두피 care 및 비만 clinic 업무까지 전담하면서 <br> 
    이 분야의 독보적인 존재로 우뚝 서기까지의 원동력은 의사 및 병원 관계자 분들의 무한한 성원에 감사 드립니다.<br> 
    <br> 
    2008년부터 준비되어 온 미국 Harvest Technologies Inc.와 협력하여 유명 대학 교수진의 도움을 받아<br>
    국내외 의료계의 유전공학 분야 발전을 위하여 Stemcell을 알리고자 준비해 온지 벌써 3년이 지났습니다.<br> 
    <br> 
    앞으로도 대한민국의 의료발전을 위해 진일보된 신뢰를 바탕으로 모범적인 회사가 되도록 <br> 
    노력 할 것입니다. 생명을 존중하는 기업 ㈜미라 앞으로도 아낌없는 격려 부탁 드립니다.<br> 
    <br> 
    감사합니다.<br> 
    <br> 
    ㈜미라 대표이사<br> 
    신현순<br> 
    <br> 
    <b>미라(Mira)란?</b><br>
    미라의 뜻은 라틴어로 ‘기적’이라는 뜻입니다.<br>
    <br>
    <b>성공철학</b><br> 
    당신이 마음속에 그린 것을 생생하게 상상하고 간절히 바라며 깊이 믿고 열의를 다해 행동하면<br>
    그것이 무슨 일이든 반드시 현실로 이루어 진다!<br> 
    <br> 
    <b>사명과 비전</b><br> 
    생명을 존중하고 건강한 삶을 추구하는 기업 미라<br> 
    Company Mira respect for life and pursue healthy life<br> 
    <br> 
    첨단진료의 전문화를 위하여 국내외 각 의료기관과 협력하여 지속적으로 연구 개발 할 것입니다.<br> 
    선진화된 의학기술을 선도하여 질병을 치유하도록 할 것입니다.<br> 
    윤리와 도덕을 중시하는 기업으로 병원의 발전과 국민건강에 이바지 할 것입니다.<br> 
    <br> 
    <b>사회공헌</b><br> 
    필리핀 팬-월드 맹인 선교회 정기후원 <br>&nbsp;&nbsp;&nbsp;&nbsp;
    - 빠딜랴 맹인 교회건축 <br>&nbsp;&nbsp;&nbsp;&nbsp;
    - 어린이 유치원 개원 <br> &nbsp;&nbsp;&nbsp;&nbsp;
    - 교회 사역 <br>&nbsp;&nbsp;&nbsp;&nbsp;
    - 비정규 학교 교육 사역 (개인 학습지도 센터) <br>&nbsp;&nbsp;&nbsp;&nbsp;
    - 조이 하우스 사역 (여자 시각장애인 그룹 홈) <br>&nbsp;&nbsp;&nbsp;&nbsp;
    - 빔 하우스 사역 (남자 시각장애인 그룹 홈) <br>&nbsp;&nbsp;&nbsp;&nbsp;
    - 급식 사역 (어린이 급식, 노인급식) <br>&nbsp;&nbsp;&nbsp;&nbsp;
    - 장학 사역 <br>&nbsp;&nbsp;&nbsp;&nbsp;
    - 의료 사역 <br>&nbsp;&nbsp;&nbsp;&nbsp;
    - 단기 선교 사역 <br>&nbsp;&nbsp;&nbsp;&nbsp;
    - 어린이 성경학교 <br>&nbsp;&nbsp;&nbsp;&nbsp;
    - 국립 맹아학교 사역 <br> 
    <br> 
    월드비전 긴급구호 식량위기 정기후원<br><img src="/system/attachments/1/standard/harvest_kor.png?1298387300"><br> 
    <br> 
    사단법인 한국청소년육성회 강남지구회 청소년 선도 및 보호 <br> 
    <br>
    <b>사업현황</b><br> 
    정형외과 Equipment Supplier<br>
    성형외과 Equipment Supplier<br>
    두피 Equipment Supplier<br>
    피부과 Equipment Supplier<br>
    비만 Equipment Supplier<br>
    <br> 
    <b>회사현황</b><br> 
    2009 미국 하버드대학 줄기세포 Harvest Technologies Inc.<br> 
    2009 영국 PANGAEA LABORATORIES Ltd. Medik8, Korea Exclusive Distributor<br> 
    2006 호주 NORSELD Pty Ltd. Dual Yellow Laser, Korea Exclusive Distributor<br> 
    2005 독일 COSMOMED Beauty-Rent GmbH, Korea Exclusive Distributor<br> 
    2004 미국 SANSPA USA, Korea Exclusive Distributor<br> 
    2002 미국 PURE OXYGEN, LLC, Korea Exclusive Distributor<br> 
    2001 프랑스 LPG Systems S.A., Korea Exclusive Distributor<br> 
    1998 이태리 CARISMA s.r.l., Korea Exclusive Distributor<br> 
    1996 프랑스 PHYTOBIODERMIE, Korea Exclusive Distributor<br> 
    1994 사이프러스 NEODERMA COSMETICS-ROLANDOS Enterprises Ltd., Korea Exclusive Distributor<br> 
    1991 이태리 SAUNA ITALIA SPA., Korea Exclusive Distributor<br> 
    1988 이태리 IPS S.R.L., Korea Exclusive Distributor<br> 
    1987 이태리 SA.MAS. s.r.l., Korea Exclusive Distributor<br> 
    1986 이태리 FORMAGGIA s.r.l., Korea Exclusive Distributor<br> 
    <br> 
    <b>회사연혁</b><br> 
    2011.02&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;㈜미라(Mira) 상호변경<br> 
    2002.06&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;㈜미라루쉬(Mirarush) 상호변경<br> 
    1997.04&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;㈜미라코스메틱 법인 전환<br> 
    &nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;미라피부과 피부맨풀 프랜차이즈 사업 시행<br> 
    1988.01&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;미라피부과 의원 개원
    <br><br><br> 

    <b>위치 및 연락처 </b><br>
    미라㈜Mira<br>
    서울시 강남구 역삼동 721-36 3층<br>
    <b>Phone</b>: 02-556-6545<br>
    <b>Fax</b>: 02-556-6768<br>
    <b>Web</b>: www.mirarush.com / www.harvest.com<br>
    <br><br>



    <h4>[하비스트 미국 본사]</h4> 
    <h5> 하비스트 대표 이사 Gary Tureski</h5>
    - 롱아일랜드대학 생물학전공 <br> 
    - 미국 면역질병 협회 <br> 
    - 의료장비기업 세일즈매니저 (1972년~1985년)<br> 
    - 하비스트 Technology 설립 (1995년) <br> 
    - 하비스트 Technology 대표이사 <br> 
    <br> 
    사업현황: 의료시스템 및 장비 <br> 
    사업목표: 환자의 골수와 혈액에서 체취한 줄기세포를 이용하여 각종 질병에 대해 자연적 치유를 도움<br> 
    <br> 
    <b>기업연혁</b><br> 
    1995년: 하비스트 설립 <br> 
    1999년 11월: SmartPRep 출시<br> 
    2001년: SmartPRep1 Disposals 1백만개 판매 <br> 
    2001년: SmartPRep1 장비 6천개 판매 <br> 
    2002년: SmartPRep2 출시<br> 
    2006년 9월: BMAC 출시 <br> 
    2006년 12월: BMAC Disposals 50,000개 판매 <br> 
    <br> 
    <b>위치 및 연락처</b> <br> 
    Harvest Technologies Corporation <br> 
    40 Grissom Road, Suite 100 <br> 
    Plymouth, MA 02360 USA<br> 
    <span style="font-weight: bold;"> Phone</span>: 508-732-7500 <br> 
    <span style="font-weight: bold;">Fax</span>: 508-732-0400<br> 
    <b>Web</b>: <a href="http://www.harvesttech.com">www.harvesttech.com</a><br> 
    <br>
</div>
<div class="main_bottom"></div>

app/views/main/new_question.html.erb
<%= render :partial => '/main/rail' %>

<div id="main_wrapper">
	<div class="main_container">

		<%= form_for '', :url => question_path, :html => { :multipart => true, :class => "new_question", :onsubmit => "zLoading();" } do |f| %>

			<div class="field">
				<%= f.label :title, "제&nbsp;&nbsp;&nbsp;&nbsp;목".html_safe %>
				<%= f.text_field :title, :class => "text", :autocomplete => "off" %>
			</div>

			<div class="field">
				<%= f.label :name, "이&nbsp;&nbsp;&nbsp;&nbsp;름".html_safe %>
				<%= f.text_field :name, :class => "text", :autocomplete => "off" %>
			</div>

			<div class="field">
				<%= f.label :email, "이메일" %>
				<%= f.text_field :email, :class => "text", :autocomplete => "off" %>
			</div>

			<div class="field">
				<%= f.label :phone, "연락처" %>
				<%= f.text_field :phone, :class => "text", :autocomplete => "off" %>
			</div>

			<div class="field">
				<%= f.label :attachment, "파일첨부" %>
				<%= f.file_field :attachment, :class => "file" %>
			</div>

			<div class="field">
				<%= f.text_area :content, :class => "text" %>
			</div>

			<div class="actions">
				<%= submit_tag("메일발송", :class => "zButton") %>
				<%= cancel_to %>
			</div>

		<% end %>


	</div>
	<div class="main_bottom"></div>

</div>

app/views/main/new_rsvp.html.erb
<div id="main_wrapper">
	<div class="main_container">
	  
	  <h2 class="new_rsvp">컨퍼런스 신청서 작성하기</h2>

		<%= form_for '', :url => rsvp_path, :html => { :multipart => true, :class => "new_question", :onsubmit => "zLoading();" } do |f| %>

			<div class="field">
				<%= f.text_field :hospital, :class => "text control_placeholder", :placeholder => "병원명", :autocomplete => "off" %>
			</div>

			<div class="field">
				<%= f.text_field :department, :class => "text control_placeholder", :placeholder => "진료과목 및 직책", :autocomplete => "off" %>
			</div>

			<div class="field">
				<%= f.text_field :name, :class => "text control_placeholder", :placeholder => "성명", :autocomplete => "off" %>
			</div>

			<div class="field">
				<%= f.text_field :phone, :class => "text control_placeholder", :placeholder => "연락처", :autocomplete => "off" %>
			</div>

			<div class="field">
				<%= f.text_field :email, :class => "text control_placeholder", :placeholder => "이메일", :autocomplete => "off" %>
			</div>

			<div class="actions">
				<%= submit_tag("참가신청서 접수", :class => "zButton") %>
				<%= cancel_to %>
			</div>

		<% end %>


	</div>
	<div class="main_bottom"></div>

</div>