config/routes.rb
Harvest::Application.routes.draw do
	match 'login' => "users#login"
	match 'logout' => "users#logout"

	resources :users do
		post :create_session, :on => :collection
	end

	resources :sections do 
		resources :folders do
			post :sort, :on => :collection
			resources :pages
			resources :boards do
				resources :posts
			end
		end
	end

	resources :questions, :comments, :assets
	
	match "editor/:action", :controller => :editor, :as => :editor, :via => [:get, :post]

	match 'new_question' => "main#new_question", :as => 'new_question'
	match 'question' => "main#question", :via => [:post], :as => 'question'
	match 'new_rsvp' => "main#new_rsvp", :as => 'new_rsvp'
	match 'rsvp' => "main#rsvp", :via => [:post], :as => 'rsvp'

	match 'company' => "main#company", :as => 'company'

	root :to => "main#index"	
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  has_attached_file :attachment, :styles => { :big => "640x480", :standard => "480x360>" }
end

app/models/board.rb
class Board < ActiveRecord::Base
	
	belongs_to :folder, :counter_cache => true
	has_many :posts, :dependent => :destroy

	def is_admin_only?
		NoticeBoardIDs.include? self.id
	end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :post, :counter_cache => true
	belongs_to :user

	def owned_by?(u)
		!u.blank? && (self.user == u || u.is_admin?)
	end

end

app/models/folder.rb
class Folder < ActiveRecord::Base

	belongs_to :section, :counter_cache => true
	has_many :pages, :dependent => :destroy
	has_many :boards, :dependent => :destroy

	acts_as_list

	scope :sequence, :order => "position asc"

	def has_multiple_items?
		self.has_multiple_pages? || self.has_multiple_boards? || self.has_both_of_page_and_board?
	end

	def has_page?
		self.pages_count > 0
	end

	def has_multiple_pages?
		self.pages_count >= 2
	end

	def has_board?
		self.boards_count > 0
	end

	def has_multiple_boards?
		self.boards_count >= 2
	end

	def has_both_of_page_and_board?
		self.has_page? && self.has_board?
	end

end

app/models/page.rb
# encoding: UTF-8
class Page < ActiveRecord::Base
	validates_presence_of :title, :message => "제목을 입력해주세요"

	belongs_to :section
	belongs_to :folder, :counter_cache => true

end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user
	belongs_to :board, :counter_cache => true
	has_many :comments, :dependent => :destroy

  has_attached_file :attachment

	def self.per_page
		15
	end

	def has_attachment?
		!self.attachment_file_name.blank? && !self.attachment_file_size.zero?
	end

	def owned_by?(u)
		!u.blank? && (self.user == u || u.is_admin?)
	end

end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/section.rb
class Section < ActiveRecord::Base

	has_many :folders, :dependent => :destroy

	def has_folder?
		self.folders_count > 0
	end

end

app/models/user.rb
# encoding: UTF-8
class User < ActiveRecord::Base

	validates_presence_of     :email, :message => "이메일을 입력해주세요."
  validates_format_of       :email, :with => /\A[\w\.%\+\-]+@(?:[A-Z0-9\-]+\.)+(?:[A-Z]{2}|com|org|net|edu|gov|mil|biz|info|mobi|name|aero|jobs|museum)\z/i, :message => "알 수 없는 형식의 이메일주소입니다."
  validates_uniqueness_of   :email, :message => "이메일이 이미 사용 중입니다."
  validates_length_of       :password, :within => 4..40, :message => "암호를 4~40자로 입력해주세요."

	attr_accessor :password_confirmation

	def self.authenticate(attrs)
		u = find_by_login(attrs[:login])
		u && u.password == attrs[:password] ? u : nil
	end

	def is_admin?
		self.level >= 9
	end

	protected
		def validate
			errors.add(:passowrd, "암호와 재확인이 다릅니다.") if self.password != @password_confirmation && self.from_crowd?
		end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/editor_helper.rb
module EditorHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= @title %>하비스트 테크놀로지스</title>
  <%= stylesheet_link_tag :all %>
	
	<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-21587372-1']);
    _gaq.push(['_setDomainName', '.co.kr']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
  
  <%= javascript_include_tag :defaults, 'wysihat', 'zlayer' %>
  <%= csrf_meta_tag %>
</head>

<body>
	<div id="wrapper">
		<div id="header">
			<div id="alert" class="fragile do_nullify"><%= flash_messages %></div>
			<%= render :partial => 'main/header' %>
		</div>

		<div id="section">
			<%= yield %>
		</div>

		<div id="footer">
			<ul id="family_sites" style="display:none" class="fragile do_hide">
				<li><%= link_to "하비스트 US", "http://www.harvesttech.com", :class => "link" %></li>
				<li><%= link_to "(주)미라", "http://mirarush.com", :class => "link" %></li>
			</ul>
			<%= link_to_function "", "$('family_sites').show()", :class => "family_site" %>
			<%= link_to_function image_tag('Index/Bottom/index_bottom_menu_01.png'), "zLayer.open('/privacy.html?s=auto')", :class => "overlay" %>
			<%= link_to_function image_tag('Index/Bottom/index_bottom_menu_02.png'), "zLayer.open('/agreement.html?s=auto')", :class => "overlay" %>
		</div>
	</div>

	<script>
    document.on("dom:loaded", function() {
			initSmartFocus();
			initLoadingImage();
			initFragileLayer();
			initControlPlaceHolder();
		});
	</script>
</body>

</html>

app/views/pages/_form.html.erb
<script type="text/javascript" charset="utf-8">
	document.on("dom:loaded", function() {
		var editor = WysiHat.Editor.attach('page_content');
		var toolbar = new WysiHat.Toolbar(editor);

		toolbar.addButton({ label: "Bold" });
		toolbar.addButton({ label: "Underline" });
		toolbar.addButton({ label: "Italic" });
		toolbar.addButton({ name: 'strikethrough', label: "Strike" });

		toolbar.addButton({
			label: "Block",
			handler: function(editor) { zLayer.open('<%= editor_path("block_selector") %>?editor_id=' + editor.id, editor.id); }
		});

		toolbar.addButton({
			label: "FontColor",
			handler: function(editor) { zLayer.open('<%= editor_path("color_picker") %>?editor_id=' + editor.id, editor.id); }
		});

		toolbar.addButton({
			label: "Left",
			handler: function(editor) { editor.alignSelection("Left"); }
		});
		toolbar.addButton({
			label: "Center",
			handler: function(editor) { editor.alignSelection("Center"); }
		});
		toolbar.addButton({
			label: "Right",
			handler: function(editor) { editor.alignSelection("Right"); }
		});

		toolbar.addButton({
			label: 'Image',
			handler: function(editor) { editor.focus(); zLayer.open('<%= editor_path("new_image") %>?editor_id=' + editor.id, editor.id); }
		});

		toolbar.addButton({
			label: 'HTML',
			handler: function(editor) { toggleHTML(editor); }
		});

		// toolbar.addButtonSet(WysiHat.Toolbar.ButtonSets.Basic);

		// Hide our error message if the editor loads fine
		$('error').hide();
	});
</script>

<%= form_for [@section, @folder, @page], :html => { :class => "new", :onsubmit => "updateWHContent();" } do |f| %>

	<% if @page.errors.any? %>
		<div id="error_explanation">
			<h4><%= @page.errors.count %>개의 문제가 있습니다.</h4>

			<ul>
			<% @page.errors.full_messages.each do |msg| %>
				<li><%= msg.gsub(/^[-_a-zA-Z0-9]+\s/,'') %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="hidden">
		<%= f.hidden_field :section_id %>
		<%= f.hidden_field :folder_id %>
	</div>

	<div class="field">
		<%= f.text_field :title, :class => "text control_placeholder", :placeholder => "페이지제목..", :autocomplete => "off" %>
	</div>

	<div class="field">
		<%= f.text_area :content, :class => "text" %>
	</div>

	<div class="actions">
		<%= submit_tag("페이지만들기", :class => "zButton") %>
		<%= cancel_to %>
	</div>

<% end %>

app/views/pages/edit.html.erb
<%= render :partial => '/main/rail' %>

<div id="main_wrapper">
	<%= admin_actions() %>
	<div class="main_container">

	<%= render 'form' %>

	</div>
	<div class="main_bottom"></div>
</div>

app/views/pages/new.html.erb
<%= render :partial => '/main/rail' %>

<div id="main_wrapper">
	<%= admin_actions %>
	<div class="main_container">

	<%= render 'form' %>

	</div>
	<div class="main_bottom"></div>

</div>

app/views/pages/show.html.erb
<%= render :partial => '/main/rail' %>

<div id="main_wrapper">
	<div class="main_container">
		<%= admin_actions("#{link_to("페이지수정", edit_section_folder_page_path(@section, @folder, @page), :class => "link")}") %>

		<div class="page">
	<!--		<h5><%= @page.title %></h5> -->
			<div class="page_content">

				<% if @page.id == 4 %>
					<%# @page.content.html_safe %>
					<%# @page.content.gsub(/[\r\n]/,'').gsub(/&lt;iframe.*?\/iframe&gt;/, "youtube").html_safe %>
					<%= @page.content.gsub(/height=\"390\"/,"height='240'").gsub(/width=\"(480|640)\"/,"width='280'").gsub(/&lt;/,"<").gsub('&gt;',">").html_safe %>
				<% else %>
					<%= @page.content.html_safe %>
				<% end %>

			</div>
		</div>
	</div>
	<div class="main_bottom"></div>
</div>