config/routes.rb
Harvest::Application.routes.draw do
	match 'login' => "users#login"
	match 'logout' => "users#logout"

	resources :users do
		post :create_session, :on => :collection
	end

	resources :sections do 
		resources :folders do
			post :sort, :on => :collection
			resources :pages
			resources :boards do
				resources :posts
			end
		end
	end

	resources :questions, :comments, :assets
	
	match "editor/:action", :controller => :editor, :as => :editor, :via => [:get, :post]

	match 'new_question' => "main#new_question", :as => 'new_question'
	match 'question' => "main#question", :via => [:post], :as => 'question'
	match 'new_rsvp' => "main#new_rsvp", :as => 'new_rsvp'
	match 'rsvp' => "main#rsvp", :via => [:post], :as => 'rsvp'

	match 'company' => "main#company", :as => 'company'

	root :to => "main#index"	
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  has_attached_file :attachment, :styles => { :big => "640x480", :standard => "480x360>" }
end

app/models/board.rb
class Board < ActiveRecord::Base
	
	belongs_to :folder, :counter_cache => true
	has_many :posts, :dependent => :destroy

	def is_admin_only?
		NoticeBoardIDs.include? self.id
	end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :post, :counter_cache => true
	belongs_to :user

	def owned_by?(u)
		!u.blank? && (self.user == u || u.is_admin?)
	end

end

app/models/folder.rb
class Folder < ActiveRecord::Base

	belongs_to :section, :counter_cache => true
	has_many :pages, :dependent => :destroy
	has_many :boards, :dependent => :destroy

	acts_as_list

	scope :sequence, :order => "position asc"

	def has_multiple_items?
		self.has_multiple_pages? || self.has_multiple_boards? || self.has_both_of_page_and_board?
	end

	def has_page?
		self.pages_count > 0
	end

	def has_multiple_pages?
		self.pages_count >= 2
	end

	def has_board?
		self.boards_count > 0
	end

	def has_multiple_boards?
		self.boards_count >= 2
	end

	def has_both_of_page_and_board?
		self.has_page? && self.has_board?
	end

end

app/models/page.rb
# encoding: UTF-8
class Page < ActiveRecord::Base
	validates_presence_of :title, :message => "제목을 입력해주세요"

	belongs_to :section
	belongs_to :folder, :counter_cache => true

end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user
	belongs_to :board, :counter_cache => true
	has_many :comments, :dependent => :destroy

  has_attached_file :attachment

	def self.per_page
		15
	end

	def has_attachment?
		!self.attachment_file_name.blank? && !self.attachment_file_size.zero?
	end

	def owned_by?(u)
		!u.blank? && (self.user == u || u.is_admin?)
	end

end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/section.rb
class Section < ActiveRecord::Base

	has_many :folders, :dependent => :destroy

	def has_folder?
		self.folders_count > 0
	end

end

app/models/user.rb
# encoding: UTF-8
class User < ActiveRecord::Base

	validates_presence_of     :email, :message => "이메일을 입력해주세요."
  validates_format_of       :email, :with => /\A[\w\.%\+\-]+@(?:[A-Z0-9\-]+\.)+(?:[A-Z]{2}|com|org|net|edu|gov|mil|biz|info|mobi|name|aero|jobs|museum)\z/i, :message => "알 수 없는 형식의 이메일주소입니다."
  validates_uniqueness_of   :email, :message => "이메일이 이미 사용 중입니다."
  validates_length_of       :password, :within => 4..40, :message => "암호를 4~40자로 입력해주세요."

	attr_accessor :password_confirmation

	def self.authenticate(attrs)
		u = find_by_login(attrs[:login])
		u && u.password == attrs[:password] ? u : nil
	end

	def is_admin?
		self.level >= 9
	end

	protected
		def validate
			errors.add(:passowrd, "암호와 재확인이 다릅니다.") if self.password != @password_confirmation && self.from_crowd?
		end
end

app/controllers/boards_controller.rb
# encoding: UTF-8
class BoardsController < ApplicationController

	before_filter :admin_required, :only => [ :new, :create, :edit, :update, :destory ]
	before_filter :find_supers
	after_filter	:store_location, :only => [ :show ]

	def new
		@board = @folder.boards.new(:section_id => @section.id)
		render :layout => false
	end

	def create
		@board = Board.new(params[:board])

		if @board.save
			flash[:notice] = "게시판이 생성되었습니다."
			render :update do |page|
				page.redirect_to [@section, @folder, @board]
			end
		else
			render :update do |page|
				page.alert @board.errors.full_messages
			end
		end
	end

	def show
		@board = Board.find(params[:id])
		@title = @board.title

		conditions = params[:q].blank? ? "" : ["title like ?", "%#{params[:q]}%"]
		@posts = @board.posts.paginate(:page => params[:page], :order => "created_at desc", :per_page => Post.per_page, :conditions => conditions)
	end

	def edit
		@board = Board.find(params[:id])

		render :layout => false
	end

	def update
		@board = Board.find(params[:id])

		if @board.update_attributes(params[:board])
			flash[:notice] = "변경되었습니다"
			render :update do |page|
				page.redirect_to [@section, @folder, @board]
			end
		else
			render :update do |page|
				page.alert @board.errors.full_messages
				page << "zDone();"
			end
		end
	end

	private
		def find_supers
			@folder = Folder.find(params[:folder_id])
			@section = Section.find(params[:section_id])
		end

end

app/controllers/main_controller.rb
# encoding: UTF-8
class MainController < ApplicationController

	def question
		Thread.new do
			UserMailer.question(params).deliver
		end

		flash[:notice] = "문의 메일이 전송되었습니다."
		redirect_to "/sections/5"
	end

	def rsvp
		Thread.new do
			UserMailer.rsvp(params).deliver
		end

		flash[:notice] = "컨퍼런스 참가 신청이 완료되었습니다."
		redirect_to "/sections/5/folders/9/boards/2/posts/28"
	end

end

app/helpers/application_helper.rb
# encoding: UTF-8
module ApplicationHelper

	def add_query(options = {})
		specified_url = options.delete(:url) || request.path
		if options.delete(:clear).blank?
			queries = (options.inject(h = {}) {|h,v| h.merge(v[0].to_s => v[1])}).reverse_merge(request.query_parameters)
		else
			queries = (options.inject(h = {}) {|h,v| h.merge(v[0].to_s => v[1])})
		end

		"#{specified_url}?#{queries.to_param}"
	end

	def admin_actions(extra = "")
		if logged_in_as_admin?
			("<div class='admin_actions'>" +
				"#{link_to_function "폴더이름변경", "zLayer.open(event, '#{edit_section_folder_path(@section, @folder)}')", :class => "link"}" +
				"#{link_to "새로운 페이지", new_section_folder_page_path(@section, @folder), :class => "link"}" +
				"#{link_to_function "게시판추가", "zLayer.open(event, '#{new_section_folder_board_path(@section, @folder)}')", :class => "link"}" +
				extra +
			"</div>").html_safe
		end
	end

	def return_url(default = "/")
		return_to = session[:return_to] || default
		session[:return_to] = session[:previous] = nil
		return_to
	end

	def cancel_to(url = nil)
		url ||= return_url
		content_tag :input, nil, :type => "button", :class => "zButton spacer", :value => "취소", :onclick => "location.href='#{url}'"
	end

	def mouseover
		{ :onmouseover => "mOver(this)", :onmouseout => "mOut(this)" }
	end

	def nl2br(text)
		text.gsub(/[\n]/, "<br/>").html_safe
	end

	def br2space(text)
		text.gsub(/<br.?>/i,' ')
	end

	def dtime_in_words(from_time)
		(distance_of_time_in_words(from_time, Time.now).gsub(/[a-z]+/i) do |m|
			{'years'=>'^년', 'year'=>'^년', 'days'=>'^일', 'day'=>'^일', 'about'=>'약 ','second'=>'^초','seconds'=>'^초','minute'=>'^분','minutes'=>'^분','hour'=>'^시간','hours'=>'^시간','a'=>1}[m]
		end).gsub(/\s\^/,'') + " 전"
	end

	def	logged_in_as_admin?
		!@current_user.blank? && @current_user.is_admin?
	end

	def	logged_in?
		!@current_user.blank?
	end

	def flash_messages
		if flash[:error]
			fl = flash[:error]
			flash[:error] = nil
		elsif flash[:notice]
			fl = flash[:notice]
			flash[:notice] = nil
		end
		fl
	end

end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/editor_helper.rb
module EditorHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/boards/edit.html.erb
<%= form_for [@section, @folder, @board], :remote => true, :html => { :onsubmit => "zLoading();" } do |f| %>
	<div class="hidden">
		<%= f.text_field :section_id, :value => @section.id %>
		<%= f.text_field :folder_id %>
	</div>

	<div class="field">
		<%= f.text_field :title, :class => "text smart_focus", :autocomplete => "off" %>
	</div>

	<div class="actions ph_child">
		<%= submit_tag("수정", :class => "zButton right") %>
	</div>
<% end %>

<script>initSmartFocus();</script>

app/views/boards/new.html.erb
<%= form_for [@section, @folder, @folder.boards.new], :remote => true, :html => { :onsubmit => "zLoading();" } do |f| %>
	<div class="hidden">
		<%= f.text_field :section_id, :value => @section.id %>
		<%= f.text_field :folder_id %>
	</div>

	<div class="field">
		<%= f.text_field :title, :class => "text smart_focus", :autocomplete => "off" %>
	</div>

	<div class="actions ph_child">
		<%= submit_tag("생성", :class => "zButton right") %>
	</div>
<% end %>

<script>initSmartFocus();</script>

app/views/boards/show.html.erb
<%= render :partial => '/main/rail' %>

<div id="main_wrapper">
	<%= admin_actions("#{link_to_function "게시판이름변경", "zLayer.open('#{edit_section_folder_board_path(@section, @folder, @board)}', event)", :class => "link"}") %>

	<div class="main_container">

	<div class="board">
		<h5><%= @board.title %></h5>

		<ul class="posts">
			<% if @posts.blank? && !params[:q].blank? %>
				<li class="empty">검색결과가 없습니다.</li>
			<% else %>
				<%= render @posts %>
			<% end %>
		</ul>

		<div class="toolbar">
			<% if (@board.is_admin_only? && logged_in_as_admin?) || !@board.is_admin_only? %>
				<%= link_to "글쓰기", new_section_folder_board_post_path(@section, @folder, @board), :class => "link" %>
			<% end %>

			<% form_tag '', :method => :get, :class => 'search' do %>
				<div class="field">
					<%= text_field_tag :q, "", :class => "text" %>
					<%= submit_tag('검색', :class => 'izButton') %>
				</div>
			<% end %>
		</div>

		<div class="paginate">
			<%= will_paginate(@posts, :previous_label => "<", :next_label => ">") %>
		</div>

	</div>

	</div>
	<div class="main_bottom"></div>

</div>