config/routes.rb
Harvest::Application.routes.draw do
	match 'login' => "users#login"
	match 'logout' => "users#logout"

	resources :users do
		post :create_session, :on => :collection
	end

	resources :sections do 
		resources :folders do
			post :sort, :on => :collection
			resources :pages
			resources :boards do
				resources :posts
			end
		end
	end

	resources :questions, :comments, :assets
	
	match "editor/:action", :controller => :editor, :as => :editor, :via => [:get, :post]

	match 'new_question' => "main#new_question", :as => 'new_question'
	match 'question' => "main#question", :via => [:post], :as => 'question'
	match 'new_rsvp' => "main#new_rsvp", :as => 'new_rsvp'
	match 'rsvp' => "main#rsvp", :via => [:post], :as => 'rsvp'

	match 'company' => "main#company", :as => 'company'

	root :to => "main#index"	
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  has_attached_file :attachment, :styles => { :big => "640x480", :standard => "480x360>" }
end

app/models/board.rb
class Board < ActiveRecord::Base
	
	belongs_to :folder, :counter_cache => true
	has_many :posts, :dependent => :destroy

	def is_admin_only?
		NoticeBoardIDs.include? self.id
	end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

	belongs_to :post, :counter_cache => true
	belongs_to :user

	def owned_by?(u)
		!u.blank? && (self.user == u || u.is_admin?)
	end

end

app/models/folder.rb
class Folder < ActiveRecord::Base

	belongs_to :section, :counter_cache => true
	has_many :pages, :dependent => :destroy
	has_many :boards, :dependent => :destroy

	acts_as_list

	scope :sequence, :order => "position asc"

	def has_multiple_items?
		self.has_multiple_pages? || self.has_multiple_boards? || self.has_both_of_page_and_board?
	end

	def has_page?
		self.pages_count > 0
	end

	def has_multiple_pages?
		self.pages_count >= 2
	end

	def has_board?
		self.boards_count > 0
	end

	def has_multiple_boards?
		self.boards_count >= 2
	end

	def has_both_of_page_and_board?
		self.has_page? && self.has_board?
	end

end

app/models/page.rb
# encoding: UTF-8
class Page < ActiveRecord::Base
	validates_presence_of :title, :message => "제목을 입력해주세요"

	belongs_to :section
	belongs_to :folder, :counter_cache => true

end

app/models/post.rb
class Post < ActiveRecord::Base

	belongs_to :user
	belongs_to :board, :counter_cache => true
	has_many :comments, :dependent => :destroy

  has_attached_file :attachment

	def self.per_page
		15
	end

	def has_attachment?
		!self.attachment_file_name.blank? && !self.attachment_file_size.zero?
	end

	def owned_by?(u)
		!u.blank? && (self.user == u || u.is_admin?)
	end

end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/section.rb
class Section < ActiveRecord::Base

	has_many :folders, :dependent => :destroy

	def has_folder?
		self.folders_count > 0
	end

end

app/models/user.rb
# encoding: UTF-8
class User < ActiveRecord::Base

	validates_presence_of     :email, :message => "이메일을 입력해주세요."
  validates_format_of       :email, :with => /\A[\w\.%\+\-]+@(?:[A-Z0-9\-]+\.)+(?:[A-Z]{2}|com|org|net|edu|gov|mil|biz|info|mobi|name|aero|jobs|museum)\z/i, :message => "알 수 없는 형식의 이메일주소입니다."
  validates_uniqueness_of   :email, :message => "이메일이 이미 사용 중입니다."
  validates_length_of       :password, :within => 4..40, :message => "암호를 4~40자로 입력해주세요."

	attr_accessor :password_confirmation

	def self.authenticate(attrs)
		u = find_by_login(attrs[:login])
		u && u.password == attrs[:password] ? u : nil
	end

	def is_admin?
		self.level >= 9
	end

	protected
		def validate
			errors.add(:passowrd, "암호와 재확인이 다릅니다.") if self.password != @password_confirmation && self.from_crowd?
		end
end

app/controllers/main_controller.rb
# encoding: UTF-8
class MainController < ApplicationController

	def question
		Thread.new do
			UserMailer.question(params).deliver
		end

		flash[:notice] = "문의 메일이 전송되었습니다."
		redirect_to "/sections/5"
	end

	def rsvp
		Thread.new do
			UserMailer.rsvp(params).deliver
		end

		flash[:notice] = "컨퍼런스 참가 신청이 완료되었습니다."
		redirect_to "/sections/5/folders/9/boards/2/posts/28"
	end

end

app/controllers/posts_controller.rb
# encoding: UTF-8
class PostsController < ApplicationController

	before_filter :login_required, :only => [ :new, :create, :edit, :update, :destory ]
	before_filter :admin_required, :only => [ :new, :create, :edit, :update, :destory ], :if => :is_notice_board
	before_filter :find_supers
	after_filter	:store_location, :only => [ :show ]

	def is_notice_board
		NoticeBoardIDs.include? params[:board_id].to_i
	end

	def new
		@post = @board.posts.new(:section_id => @section.id, :folder_id => @folder.id)
	end

	def create
		@post = Post.new(params[:post].merge(:user_id => @current_user.id))

		if @post.save
			redirect_to([@section, @folder, @board, @post], :notice => "글이 등록되었습니다")
		else
		end
	end

	def show
		@post = Post.find(params[:id])
		@post.increment!(:hits)
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])
		if @post.update_attributes(params[:post])
			flash[:notice] = "수정되었습니다"
			redirect_to [@section, @folder, @board, @post]
		else
			flash[:error] = "수정에 실패했습니다"
			render :edit
		end
	end

	private
		def find_supers
			@folder = Folder.find(params[:folder_id])
			@section = Section.find(params[:section_id])
			@board = Board.find(params[:board_id])
		end

end

app/helpers/application_helper.rb
# encoding: UTF-8
module ApplicationHelper

	def add_query(options = {})
		specified_url = options.delete(:url) || request.path
		if options.delete(:clear).blank?
			queries = (options.inject(h = {}) {|h,v| h.merge(v[0].to_s => v[1])}).reverse_merge(request.query_parameters)
		else
			queries = (options.inject(h = {}) {|h,v| h.merge(v[0].to_s => v[1])})
		end

		"#{specified_url}?#{queries.to_param}"
	end

	def admin_actions(extra = "")
		if logged_in_as_admin?
			("<div class='admin_actions'>" +
				"#{link_to_function "폴더이름변경", "zLayer.open(event, '#{edit_section_folder_path(@section, @folder)}')", :class => "link"}" +
				"#{link_to "새로운 페이지", new_section_folder_page_path(@section, @folder), :class => "link"}" +
				"#{link_to_function "게시판추가", "zLayer.open(event, '#{new_section_folder_board_path(@section, @folder)}')", :class => "link"}" +
				extra +
			"</div>").html_safe
		end
	end

	def return_url(default = "/")
		return_to = session[:return_to] || default
		session[:return_to] = session[:previous] = nil
		return_to
	end

	def cancel_to(url = nil)
		url ||= return_url
		content_tag :input, nil, :type => "button", :class => "zButton spacer", :value => "취소", :onclick => "location.href='#{url}'"
	end

	def mouseover
		{ :onmouseover => "mOver(this)", :onmouseout => "mOut(this)" }
	end

	def nl2br(text)
		text.gsub(/[\n]/, "<br/>").html_safe
	end

	def br2space(text)
		text.gsub(/<br.?>/i,' ')
	end

	def dtime_in_words(from_time)
		(distance_of_time_in_words(from_time, Time.now).gsub(/[a-z]+/i) do |m|
			{'years'=>'^년', 'year'=>'^년', 'days'=>'^일', 'day'=>'^일', 'about'=>'약 ','second'=>'^초','seconds'=>'^초','minute'=>'^분','minutes'=>'^분','hour'=>'^시간','hours'=>'^시간','a'=>1}[m]
		end).gsub(/\s\^/,'') + " 전"
	end

	def	logged_in_as_admin?
		!@current_user.blank? && @current_user.is_admin?
	end

	def	logged_in?
		!@current_user.blank?
	end

	def flash_messages
		if flash[:error]
			fl = flash[:error]
			flash[:error] = nil
		elsif flash[:notice]
			fl = flash[:notice]
			flash[:notice] = nil
		end
		fl
	end

end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/editor_helper.rb
module EditorHelper
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/_form.html.erb
<script type="text/javascript" charset="utf-8">
	document.on("dom:loaded", function() {
		var editor = WysiHat.Editor.attach('post_content');
		var toolbar = new WysiHat.Toolbar(editor);

		toolbar.addButton({ label: "Bold" });
		toolbar.addButton({ label: "Underline" });
		toolbar.addButton({ label: "Italic" });
		toolbar.addButton({ name: 'strikethrough', label: "Strike" });

		toolbar.addButton({
			label: 'Image',
			handler: function(editor) { editor.focus(); zLayer.open('<%= editor_path("new_image") %>?editor_id=' + editor.id, editor.id); }
		});

		toolbar.addButton({
			label: 'HTML',
			handler: function(editor) { toggleHTML(editor); }
		});

		// toolbar.addButtonSet(WysiHat.Toolbar.ButtonSets.Basic);

		// Hide our error message if the editor loads fine
		$('error').hide();
	});
</script>

<%= form_for [@section, @folder, @board, @post], :html => { :multipart => true, :class => "new", :onsubmit => "zLoading();updateWHContent();" } do |f| %>

	<% if @post.errors.any? %>
		<div id="error_explanation">
			<h4><%= @post.errors.count %>개의 문제가 있습니다.</h4>

			<ul>
			<% @post.errors.full_messages.each do |msg| %>
				<li><%= msg.gsub(/^[-_a-zA-Z0-9]+\s/,'') %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="hidden">
		<%= f.hidden_field :section_id %>
		<%= f.hidden_field :folder_id %>
		<%= f.hidden_field :board_id %>
	</div>

	<div class="field">
		<%= f.text_field :title, :class => "text control_placeholder", :placeholder => "글 제목..", :autocomplete => "off" %>
	</div>

	<div class="field">
		<%= f.label :attachment, "파일첨부" %>
		<%= f.file_field :attachment, :class => "file" %>
	</div>

	<div class="field">
		<%= f.text_area :content, :class => "text" %>
	</div>

	<div class="actions">
		<%= submit_tag("글 남기기 ", :class => "zButton") %>
		<%= cancel_to %>
	</div>

<% end %>

app/views/posts/_post.html.erb
<%= content_tag_for :li, post do %>

	<% cur_page = params[:page].blank? ? 1 : params[:page].to_i %>
	<div class="f post_id">
		<%= @board.posts_count - (Post.per_page * (cur_page - 1)) - post_counter %>
	</div>

	<div class="f post_title">
		<%= link_to post.title, [@section, @folder, @board, post] %>
	</div>

	<div class="f post_user">
		<%= post.user.login %>
	</div>

	<div class="f post_date">
		<%= post.created_at.strftime("%Y.%m.%d") %>
	</div>

	<div class="f post_hits">
		<%= number_with_delimiter(post.hits) %>
	</div>

<% end %>

app/views/posts/edit.html.erb
<%= render :partial => '/main/rail' %>

<div id="main_wrapper">
	<%= admin_actions %>

	<%= render 'form' %>

</div>

app/views/posts/new.html.erb
<%= render :partial => '/main/rail' %>

<div id="main_wrapper">
	<%= admin_actions %>
	<div class="main_container">

		<%= render 'form' %>

	</div>
	<div class="main_bottom"></div>

</div>

app/views/posts/show.html.erb
<%= render :partial => '/main/rail' %>

<div id="main_wrapper">
	<%= admin_actions %>

	<div class="main_container">
	<div class="post">

		<h5><%= @post.title %></h5>

		<!--
		<div class="post_byline">
			<%# @post.user.login %>
			<%# @post.created_at.strftime("%Y.%m.%d") %>
		</div>
		-->

		<% if @post.has_attachment? %>
			<div class="post_attachment">
				첨부파일: <%= link_to @post.attachment_file_name, @post.attachment.url, :class => "link", :target => "_blank" %>
			</div>
		<% end %>

		<div class="post_content">
			<% if /image/i.match(@post.attachment_content_type) %>
				<div class="attachment_image">
					<%= image_tag(@post.attachment.url) %>
				</div>
				<%=%>
			<% end %>
			<%= @post.content.html_safe %>
		</div>

		<% if @post.owned_by?(@current_user) %>
			<div class="owner_action">
				<%= link_to "수정", edit_section_folder_board_post_path(@section, @folder, @board, @post), :class => "link" %>
				<%= link_to "삭제", [@section, @folder, @board, @post], :remote => true, :method => :delete, :confirm => "삭제하시겠습니까?", :class => "link" %>
			</div>
		<% end %>

		<div class="comments">
			<%= form_for @post.comments.new, :remote => true, :html => { :onsubmit => "zLoading();" } do |f| %>
				<div class="hidden">
					<%= f.text_field :post_id, :value => @post.id %>
				</div>

				<div class="field">
					<%= f.text_area :content, :class => "text" %>
				</div>

				<div class="actions">
					<%= submit_tag("댓글남기기", :class => "zButton") %>
				</div>
			<% end %>
		</div>

		<ul id="comments">
			<%= render @post.comments.order("id desc") %>
		</ul>

		<div class="toolbar">
			<%= link_to "목록으로", [@section, @folder, @board], :class => "link" %>
		</div>

	</div> <!-- post -->
	</div>
	<div class="main_bottom"></div>
</div>